name: 'test'

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'macos-latest'
        - 'ubuntu-latest'
        - 'windows-latest'

    runs-on: '${{ matrix.os }}'

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-go@v4'
      with:
        go-version: '1.19'

    - run: 'go mod download'

    - name: 'Test'
      run: 'make test-acc'
